### ISSUE TITLE
[Android] [NPE] App crashes just after change to "My Wallet" screen

### ISSUE THREAD

**Issue by burakozhan** [helium/hotspot-app#1052]
**Describe the bug**
Android App crashes with a Null Pointer Exception a couple seconds after the user changes to the 2nd tab (My Wallet). Probably that time is variable as it seems some API returning data. 
This crash happens as of 8th November 2021, it was not happening before. Maybe some external 3rd party API changed their data structure.

**To Reproduce**

1. Start from completely closed app.
2. Open App and authenticate (fingerprint or pin code).
3. See Hotspots tab without problems.
4. Change to tab 3 (Notifications) or tab 4 (settings), notice there is no problem on those.
5. Change to tab 2 (My Wallet). 
6. Wait a couple seconds, until the api call is finished
7. App crashes and closes
8. User is back on android launcher

**Expected behavior**
Obvious, app shall not crash. App shall show My Wallet screen with data.

**Screenshots**
Not applicable, as with the crash the app closes.

**Smartphone (please complete the following information):**

- Device: Xiaomi mi 10 T Pro
- OS: Android 11, MIUI 12.5.5, Secority Patch level 2021-10-01
- App Version: 3.8.0 (Loaded from Play Store)

**Additional context**

Stacktrace: 

```
2021-11-08 09:12:42.018 18631-18631/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.helium.wallet, PID: 18631
    com.facebook.react.uimanager.IllegalViewOperationException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
        at com.facebook.react.ReactRootView.handleException(ReactRootView.java:715)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:749)
        at android.view.View.updateDisplayListIfDirty(View.java:21358)
        at android.view.View.draw(View.java:22229)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
        at android.view.View.draw(View.java:22509)
        at android.widget.ScrollView.draw(ScrollView.java:1833)
        at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:519)
        at android.view.View.updateDisplayListIfDirty(View.java:21367)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.View.draw(View.java:22229)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4310)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
        at android.view.View.updateDisplayListIfDirty(View.java:21358)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
2021-11-08 09:12:42.018 18631-18631/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4535)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4508)
        at android.view.View.updateDisplayListIfDirty(View.java:21325)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
2021-11-08 09:12:42.018 18631-18631/? E/AndroidRuntime:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:567)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:651)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4284)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3989)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3250)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2076)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8506)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
        at android.view.Choreographer.doCallbacks(Choreographer.java:897)
        at android.view.Choreographer.doFrame(Choreographer.java:826)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
        at org.reactnative.maskedview.RNCMaskedView.updateBitmapMask(RNCMaskedView.java:81)
        at org.reactnative.maskedview.RNCMaskedView.dispatchDraw(RNCMaskedView.java:35)
        at android.view.View.updateDisplayListIfDirty(View.java:21358)
        at android.view.View.draw(View.java:22229)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4551)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4334)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
        	... 128 more

```

**Comment by burakozhan** [comment]
Additional Info: 
- App still crashes if I go to settings and deactivate "Convert HNT to Currency".
- App does not crash when the bottom section on the "My Wallet" screen fails to load completely. "Failed to load. Tap to try again" will apper below "All Activity". When I tap to reload it will crash (after a while) or again state "Failed to load".

Maybe this helps close down on the broken API.

The bug is severe, since I now can't send payments due to the app crashing.

**Comment by cokes518** [comment]
We're looking into it. Can you share your wallet address so we can look for additional crash logs?

**Comment by burakozhan** [comment]
@cokes518 
is that wallet address still relevant ? 
14U4zm4fuPksK56oo6nqbtgUxwBKwUmnY6sQXExpoK5gB5YoHJP

**Comment by LoveisFree1** [comment]
Any fix for this Im having the same issue ?

**Comment by renatototo** [comment]
> 
> 
> Any fix for this Im having the same issue ?

Android. Updated from 3.8.0 to 3.8.2. Fixes this error and the "Add hotspot" issue for me. Great job.

**Comment by LoveisFree1** [comment]
Awesome thanks
