### ISSUE TITLE
Cannot start scanning operation

### ISSUE THREAD

**Issue by OzzieOrca** [helium/hotspot-app#690]
**Describe the bug**
Trying to pair with my hotspot to change the Wi-Fi network throws `Cannot start scanning operation` as a React Native error popup.
<img alt="Helium BLE Error" src="https://user-images.githubusercontent.com/756501/122126788-1a75cf80-cde7-11eb-9d74-481a6e06bf0d.png" width="300" /> <img alt="Helium BLE Error Callstack" src="https://user-images.githubusercontent.com/756501/122126793-1ba6fc80-cde7-11eb-817f-5a4bc76392a0.png" width="300" />

With the following log from Flipper:
```
Error while calling the start scan function
java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@449db14b: GattService registerScanner
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2418)
	at android.os.Parcel.createException(Parcel.java:2402)
	at android.os.Parcel.readException(Parcel.java:2385)
	at android.os.Parcel.readException(Parcel.java:2327)
	at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:1727)
	at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:425)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:277)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:153)
	at com.polidea.rxandroidble.internal.util.RxBleAdapterWrapper.startLeScan(RxBleAdapterWrapper.java:50)
	at com.polidea.rxandroidble.internal.operations.ScanOperationApi21.startScan(ScanOperationApi21.java:83)
	at com.polidea.rxandroidble.internal.operations.ScanOperationApi21.startScan(ScanOperationApi21.java:22)
	at com.polidea.rxandroidble.internal.operations.ScanOperation.protectedRun(ScanOperation.java:41)
	at com.polidea.rxandroidble.internal.QueueOperation$1.call(QueueOperation.java:42)
	at com.polidea.rxandroidble.internal.QueueOperation$1.call(QueueOperation.java:38)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:72)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**To Reproduce**

1. Go to Hotspot Settings
2. Click on 'Pair'
3. See error

**Expected behavior**
Should be able to pair with hotspot and change WiFi network

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Google Pixel 3 XL
- OS: Android 12 SPB2.210513.007
- App Version: 3.3.0 running locally from the `main` branch (commit 31f75a3ab19bee10e619dc9a78e2e02ee4f2fca2). I needed https://github.com/helium/hotspot-app/pull/679 otherwise the app just crashes here instead.

**Additional context**
@matthewcarlreetz Thanks for fixing the crash. Wondering if you had any insight here. I tried adding the new `<uses-permission android:name="android.permission.BLUETOOTH_SCAN" />` for Android 12 but I get the same error.

**Comment by OzzieOrca** [comment]
Well it works today... 🤷‍♂️
