### ISSUE TITLE
App crashes when pressing "Pair" button

### ISSUE THREAD

**Issue by zboing** [helium/hotspot-app#945]
**Describe the bug**
The app crashes when pressing "Pair" button and location is not active on older android versions

**To Reproduce**

1. Use an Android device lower or equal to 9 version (Huawei P10 in my case)
2. Location deactivated
3. Hotspot paired before and present in the list
4. Press the "Pair" button

**Expected behavior**
App should not need location by that time or ask user location permission if necessary

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Huawei P10
- OS: Android 9
- App Version 3.5.0

**Additional context**

**Comment by matthewcarlreetz** [comment]
Location permission is required to use bluetooth on android. The app should prompt for permission after you press the "Pair" button. I tested on a Samsung S6 with Android 7 and was unable to reproduce the crash.

![IMG_8506](https://user-images.githubusercontent.com/1760821/135514263-d08bb38c-506b-4be1-aa00-e65e0132cfa9.jpg)

**Comment by cokes518** [comment]
@zboing see if you can reproduce this, or provide us with your wallet address so we can look for crash logs. otherwise we'll have to close this as unable to reproduce.

**Comment by zboing** [comment]
> Location permission is required to use bluetooth on android. The app should prompt for permission after you press the "Pair" button. I tested on a Samsung S6 with Android 7 and was unable to reproduce the crash.
> 
> ![IMG_8506](https://user-images.githubusercontent.com/1760821/135514263-d08bb38c-506b-4be1-aa00-e65e0132cfa9.jpg)

On Huawei phones users can cancel the location prompt and are able to press the Pair button after enabling bluetooth.

**Comment by zboing** [comment]
> @zboing see if you can reproduce this, or provide us with your wallet address so we can look for crash logs. otherwise we'll have to close this as unable to reproduce.

My wallet address is: 142Tbz2kLTgwX2xW7yE9TZSfaHWKXneZvrRD7ziPQtRjH77UVXt
Below a piece of code when the crash occurrs: 
2021-10-01 09:48:25.268 28218-28252/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.helium.wallet, PID: 28218
    com.facebook.react.common.JavascriptException: BleError: Location services are disabled, js engine: hermes, stack:
    o@1:121452
    anonymous@1:2513716
    h@1:2513424
    anonymous@1:2513272
    anonymous@1:2517945
    value@1:98324
    value@1:108413
    anonymous@1:106891
    value@1:107857
    value@1:106849
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:216)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:784)

**Comment by derEremit** [comment]
I just have the same issue. App just closes when pressing Pair.
tested on 2 devices
Oneplus 7 Pro with vendor Android 12
Pixel 6A with grapheneos Android 13
